const mongoose=require('mongoose')

const PersonalSchema = new mongoose.Schema({
    name:{
        type:String
    },
    address:{
        type:String
    },
    email:{
        type:String
    },
    mobile:{
        type:String
    },
    linkedin:{
        type:String
    },
    github:{
        type:String
    },
    skill:{
        type:String
    },
    rname1:{
        type:String
    },
    raddress1:{
        type:String
    },
    rmobile1:{
        type:String
    },
    rname2:{
        type:String
    },
    raddress2:{
        type:String
    },
    rmobile2:{
        type:String
    },
    carrier:{
        type:String
    },
    degree1:{
        type:String
    },
    colleage1:{
        type:String
    },
    year1:{
        type:String
    },
    score1:{
        type:String
    },
    degree2:{
        type:String
    },
    colleage2:{
        type:String
    },
    year2:{
        type:String
    },
    score2:{
        type:String
    },
    degree3:{
        type:String
    },
    colleage3:{
        type:String
    },
    year3:{
        type:String
    },
    score3:{
        type:String
    },
    degree4:{
        type:String
    },
    colleage4:{
        type:String
    },
    year4:{
        type:String
    },
    score4:{
        type:String
    },
    project1:{
        type:String
    },
    project2:{
        type:String
    },
    project3:{
        type:String
    },
    project4:{
        type:String
    },
    certificate1:{
        type:String
    },
    certificate2:{
        type:String
    },
    certificate3:{
        type:String
    },
    certificate4:{
        type:String
    },
    image:{
        type:String
    }
})

const PersonalModel=mongoose.model("personal",PersonalSchema);

module.exports=PersonalModel;